import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getKindeServerSession, LoginLink, RegisterLink } from "@kinde-oss/kinde-auth-nextjs/server";
import AuthNav from "@/components/AuthNav";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/Navbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";
const { getUser } = getKindeServerSession()

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-5 flex flex-col h-screen`}
      >
        <div className="flex">
          <SidebarProvider>
            <AppSidebar />
            <main className="w-screen">
                <Navbar />
                {children}
            </main>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
